services:
  - type: web
    name: ojasneuro-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://ojasneuro.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ojasneuro-db
          property: connectionString

databases:
  - name: ojasneuro-db
    plan: free
